name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend:
    name: Backend (RuboCop)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.x
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop
        run: bundle exec rubocop

  frontend:
    name: Frontend (Build)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Check for committed node_modules
        run: |
          if git ls-files | grep -q "^node_modules/"; then
            echo "❌ node_modules/ directory is committed to Git! Please add it to .gitignore file"
            exit 1
          else
            echo "✅ No node_modules/ found."
          fi

      - name: Build
        run: npm run build
