name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend:
    name: Backend (RuboCop & Tests)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      postgres:
        image: postgres:14
        env:
          RAILS_ENV: test
          DB_USER: postgres
          DB_HOST: localhost
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DB_NAME: mood_tracker_test
        ports: 
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Prepare database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run tests
        run: bundle exec rspec spec --format documentation


  frontend:
    name: Frontend (Build)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Check for committed node_modules
        run: |
          if git ls-files | grep -q "^node_modules/"; then
            echo "❌ node_modules/ directory is committed to Git! Please add it to .gitignore file"
            exit 1
          else
            echo "✅ No node_modules/ found."
          fi
